#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    if len(n) <= 1 and k == 1 :
        return int(n)
        
    rangeSum = 0
    for i in range(len(n)):
        rangeSum += (int(n[i]) * k)

        
    def Ksum(currSum):
        if int(currSum) - 10 < 0:
            return int(currSum)
       
        curr = 0
        for i in currSum:
            curr += int(i)
        return Ksum(str(curr))
            
            
    return Ksum(str(rangeSum))
            
        
            
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()
